apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: {{ .Release.Name }}-subscription
  namespace: {{.Values.namespace}}
  labels:
    name: kyma-cap-s4ems
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.internal.bp.notification.v1
  protocol: ""
  protocolsettings: {}
  sink: http://{{ .Release.Name }}-qrcodegenerator.{{.Values.namespace}}.svc.cluster.local #this is the service name and port