apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: {{ .Release.Name }}-subscription
  namespace: {{.Values.namespace}}
  labels:
    name: kyma-cap-s4ems
spec:
  typeMatching: standard
  source: /default/bp.ems/bpems
  types:
    - bp.notification.v1
  sink: http://{{ .Release.Name }}-qrcodegenerator.{{.Values.namespace}}.svc.cluster.local #this is the service name and port
  config:
    maxInFlightMessages: "10"